---
name: YAML Lint

on:
  push:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
  workflow_dispatch:


jobs:
  call-workflow:
    uses: Devirthas/gha_yaml_called/.github/workflows/yaml-lint.yml@main 
    with:
      yaml_files: "*.yaml **/*.yaml"
